### ISSUE TITLE
fix: Supabase setup prob

### ISSUE THREAD

**Issue by dakshsinghrathore** [version0chiro/x-ama#5]
![image](https://github.com/version0chiro/x-ama/assets/115932772/cbeb1d2b-ad80-45a8-80e4-67070cb456b2)

![image](https://github.com/version0chiro/x-ama/assets/115932772/623c8fce-97fb-4048-9bae-98c94d297e97)

While setting up Supabase locally according to the project's README, I found that it's necessary to delete the default `config.toml` file that comes with the fork. After successfully installing Supabase, you should run `supabase start` instead. This worked for me.

``` bash
sudo supabase start
```
### Once this command is executed, it creates a new `config.toml` file with the desired output shown below. ⬇️

![image](https://github.com/version0chiro/x-ama/assets/115932772/12e80670-a891-435b-ac95-62f3f5f43568)

![image](https://github.com/version0chiro/x-ama/assets/115932772/072fb9d9-55fd-4e9c-aaeb-9d82d832fca3)

 ### Shall we pass the config.toml to .gitignore to fix this issue?

**Comment by version0chiro** [comment]
Good call out, if it is not impacting the system can do

**Comment by dakshsinghrathore** [comment]
@version0chiro How about I update setup guidelines for contributors and also pass the config.toml to .gitignore in a single PR ?

**Comment by version0chiro** [comment]
Works for me
